name: wotta_core
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: paolo <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  built_redux: ^7.5.0
  built_value: ^6.1.2
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.10.0
  built_value_generator: ^6.1.2
