name: land
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: paolo <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  uri: ^0.11.3+1
  js: ^0.6.0
  over_react: ^3.1.0-alpha
  qr: ^1.2.0
  wotta_core:
    path: ../wotta_core
#  path: ^1.4.1

#dependency_overrides:
#  react:
#    git:
#      url: https://github.com/cleandart/react-dart
#      ref: 5.1.0-wip
#  over_react:
#    git:
#      url: https://github.com/Workiva/over_react
#      ref: 3.1.0-wip

dev_dependencies:
  build_runner: ^1.7.0
  build_test: ^0.10.8
  build_web_compilers: ^2.12.0
  dart_dev: ^2.2.0
  dart_style: ^1.2.7
  over_react_test: ^2.5.1
  test: ^1.6.10
  pedantic: ^1.7.0

