apiVersion: v1
kind: Service
metadata:
  name: wotta
  labels:
    app: wotta
spec:
  ports:
    - port: 80
      name: web
      targetPort: 8080
  clusterIP: None
  selector:
    app: wotta
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wotta-server
spec:
  serviceName: "wotta"
  replicas: 3
  selector:
    matchLabels:
      app: wotta
  template:
    metadata:
      labels:
        app: wotta
    spec:
      containers:
        - name: wotta
          image: ppanconi/wotta-server:0.1.1
          ports:
            - containerPort: 8080
              name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wotta
spec:
  ingressClassName: nginx
  rules:
    - host: wotta.fit
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wotta
                port:
                  number: 80